# --- General options --- #

# url is the full website URL
# baseurl is the website's URL without the hostname

# If you are building a simple GitHub user page (http://username.github.io) then use these settings:
url: "https://snehabhakare.github.io"
baseurl: ""
future: true

# If you are building a GitHub project page then use these settings:
#url: "http://username.github.io/projectname"
#baseurl: "/projectname"

# Of course don't forget to change the username and projectname to YOUR username and project

# Name of website
title: Sneha Bhakare

# Short description of your site
description: The page will be updated soon!

# --- Footer options --- #

# Change all these values or delete the ones you don't want.
# Important: you must keep the "name" parameter, everything else you can remove
author:
  name: Rohit Kumar Jena
  email: "snehabhakare5@gmail.com"
  facebook: sneha.bhakare.7
  github: snehabhakare
  linkedin: 
  stackoverflow:
 
# Select which links to show in the footer
footer-links-active:
  rss: true
  facebook: true
  email: true
  github: true
  linkedin: false
  stackoverflow: false

# How to display the link to the website in the footer
# Remove this if you don't want a link in the footer
url-pretty: "snehabhakare.github.io"  # eg. "deanattali.com/beautiful-jekyll"

# --- Don't need to touch anything below here (but you can if you want) --- #

# Output options (more information on Jekyll's site)
timezone: "GMT+05:30"
markdown: kramdown
highlighter: rouge
# permalink: /:year-:month-:day-:title/
paginate: 5
paginate_path: "/blog/posts:num/"
kramdown:
  input: GFM

# Default YAML values (more information on Jekyll's site)
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true  # add comments to all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

gems:
  - jekyll-paginate
