# Site Settings


# Name of your site (displayed in the header)
myname: Sneha Bhakare
alias: Sneha
# Short bio or description (displayed in the header)
byline: 

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: https://avatars2.githubusercontent.com/u/34890579?s=400&u=9f4eb95564f407da7be71ccca29f9bf70139ccc6&v=4

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: snehabhakare5
  facebook:
  flickr:
  github: snehabhakare
  instagram:
  linkedin: snehabhakare
  pinterest:
  rss: # just type anything here for a working RSS icon
  twitter: 
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  youtube: # channel/<your_long_string> or user/<user-name>
  googleplus: # anything in your profile username that comes after plus.google.com/


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus: Sneha

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics:

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: "http://snehabhakare.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""


title: Sneha Bhakare
email: snehabhakare5@gmail.com

github_username:  snehabhakare
facebook_username: Sneha Bhakare
linkedin_username: Sneha Bhakare
facebook_id: sneha.bhakare7
linkedin_id: sneha-bhakare-0407a3134
address: Indian Institue of Technology, Bombay Mumbai-400076, India
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
plugins:
  - jekyll-redirect-from
whitelist:
  - jekyll-redirect-from
